version: '2'
services:
  base:
    build: .
    image: fpierre/ms-crm-starter

  agency-service:
    extends: base
    command: yarn start
    depends_on:
      - postgres

  postgres:
    image: sameersbn/postgresql:9.6-1
    environment:
      - DB_USER=cote
      - DB_PASS=ohgath2ig8eoP8
      - DB_NAME=cote
